"""add honor number

Revision ID: 3c4d4a35ae16
Revises: 4079f63499fe
Create Date: 2026-06-24 16:28:32.548653
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '3c4d4a35ae16'
down_revision: Union[str, None] = '4079f63499fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('honor_records', sa.Column('honor_number', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('honor_records', 'honor_number')
    # ### end Alembic commands ###

