"""add entity industry type

Revision ID: 4079f63499fe
Revises: d35c9c7eb685
Create Date: 2026-06-24 16:00:25.423307
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '4079f63499fe'
down_revision: Union[str, None] = 'd35c9c7eb685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_entities', sa.Column('entity_industry_type', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_entities', 'entity_industry_type')
    # ### end Alembic commands ###

