"""initial schema

Revision ID: d35c9c7eb685
Revises: 
Create Date: 2026-06-24 15:59:36.817406
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'd35c9c7eb685'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_card_number', sa.String(length=18), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('age_snapshot', sa.Integer(), nullable=True),
    sa.Column('ethnicity', sa.String(length=50), nullable=True),
    sa.Column('native_place', sa.String(length=200), nullable=True),
    sa.Column('district_county', sa.String(length=200), nullable=True),
    sa.Column('political_status', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('health_status', sa.String(length=100), nullable=True),
    sa.Column('professional_title', sa.String(length=100), nullable=True),
    sa.Column('wechat', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('household_type', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('home_address', sa.Text(), nullable=True),
    sa.Column('talent_category', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('administrative_position', sa.String(length=200), nullable=True),
    sa.Column('social_part_time_positions', sa.Text(), nullable=True),
    sa.Column('source_excel_row', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_district_county'), 'students', ['district_county'], unique=False)
    op.create_index(op.f('ix_students_id_card_number'), 'students', ['id_card_number'], unique=True)
    op.create_index(op.f('ix_students_name'), 'students', ['name'], unique=False)
    op.create_index('ix_students_name_district', 'students', ['name', 'district_county'], unique=False)
    op.create_index(op.f('ix_students_phone'), 'students', ['phone'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_table', sa.String(length=100), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('before_data', sa.Text(), nullable=True),
    sa.Column('after_data', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('backup_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backup_file_path', sa.Text(), nullable=False),
    sa.Column('database_type', sa.String(length=50), nullable=False),
    sa.Column('backup_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('entity_name', sa.String(length=300), nullable=True),
    sa.Column('entity_intro', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=150), nullable=True),
    sa.Column('entity_subtype', sa.String(length=150), nullable=True),
    sa.Column('established_date', sa.Date(), nullable=True),
    sa.Column('registered_address', sa.Text(), nullable=True),
    sa.Column('unified_social_credit_code', sa.String(length=50), nullable=True),
    sa.Column('industry_years', sa.Integer(), nullable=True),
    sa.Column('student_position_in_entity', sa.String(length=200), nullable=True),
    sa.Column('patent_applications', sa.Text(), nullable=True),
    sa.Column('farmer_households_driven', sa.Integer(), nullable=True),
    sa.Column('technical_partner_count', sa.Integer(), nullable=True),
    sa.Column('technical_partners', sa.Text(), nullable=True),
    sa.Column('quality_inspection_org', sa.String(length=100), nullable=True),
    sa.Column('quality_system_certification', sa.Text(), nullable=True),
    sa.Column('green_organic_geo_certification', sa.Text(), nullable=True),
    sa.Column('entity_honors', sa.Text(), nullable=True),
    sa.Column('supporting_policies', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_entities_entity_name'), 'business_entities', ['entity_name'], unique=False)
    op.create_index(op.f('ix_business_entities_student_id'), 'business_entities', ['student_id'], unique=False)
    op.create_index(op.f('ix_business_entities_unified_social_credit_code'), 'business_entities', ['unified_social_credit_code'], unique=False)
    op.create_table('cultivation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('cultivation_year', sa.Integer(), nullable=True),
    sa.Column('cultivation_needs', sa.Text(), nullable=True),
    sa.Column('training_experience', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cultivation_records_student_id'), 'cultivation_records', ['student_id'], unique=False)
    op.create_table('education_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('education_level', sa.String(length=100), nullable=True),
    sa.Column('graduate_school', sa.String(length=200), nullable=True),
    sa.Column('major', sa.String(length=200), nullable=True),
    sa.Column('certificate_number', sa.String(length=100), nullable=True),
    sa.Column('learning_experience', sa.Text(), nullable=True),
    sa.Column('work_experience', sa.Text(), nullable=True),
    sa.Column('training_experience', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('honor_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('honor_time', sa.Date(), nullable=True),
    sa.Column('honor_level', sa.String(length=100), nullable=True),
    sa.Column('honor_description', sa.Text(), nullable=False),
    sa.Column('source_column_group', sa.String(length=50), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_honor_records_student_id'), 'honor_records', ['student_id'], unique=False)
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=False),
    sa.Column('stored_file_path', sa.Text(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('sheet_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('success_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('new_rows', sa.Integer(), nullable=False),
    sa.Column('updated_rows', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batches_file_hash'), 'import_batches', ['file_hash'], unique=False)
    op.create_table('annual_revenue_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_entity_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('operating_revenue', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net_profit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('fixed_asset_net_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_assets', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_liabilities', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('current_assets', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('management_expense', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('government_subsidy_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('source_column_group', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_entity_id'], ['business_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_entity_id', 'year', name='uq_entity_revenue_year')
    )
    op.create_index(op.f('ix_annual_revenue_records_business_entity_id'), 'annual_revenue_records', ['business_entity_id'], unique=False)
    op.create_table('import_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('excel_row_number', sa.Integer(), nullable=False),
    sa.Column('column_name', sa.String(length=200), nullable=True),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_errors_import_batch_id'), 'import_errors', ['import_batch_id'], unique=False)
    op.create_table('main_industries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_entity_id', sa.Integer(), nullable=False),
    sa.Column('industry_name', sa.String(length=300), nullable=False),
    sa.Column('three_year_total_income', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('operation_years', sa.Integer(), nullable=True),
    sa.Column('source_column_group', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_entity_id'], ['business_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_main_industries_business_entity_id'), 'main_industries', ['business_entity_id'], unique=False)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_main_industries_business_entity_id'), table_name='main_industries')
    op.drop_table('main_industries')
    op.drop_index(op.f('ix_import_errors_import_batch_id'), table_name='import_errors')
    op.drop_table('import_errors')
    op.drop_index(op.f('ix_annual_revenue_records_business_entity_id'), table_name='annual_revenue_records')
    op.drop_table('annual_revenue_records')
    op.drop_index(op.f('ix_import_batches_file_hash'), table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_index(op.f('ix_honor_records_student_id'), table_name='honor_records')
    op.drop_table('honor_records')
    op.drop_table('education_records')
    op.drop_index(op.f('ix_cultivation_records_student_id'), table_name='cultivation_records')
    op.drop_table('cultivation_records')
    op.drop_index(op.f('ix_business_entities_unified_social_credit_code'), table_name='business_entities')
    op.drop_index(op.f('ix_business_entities_student_id'), table_name='business_entities')
    op.drop_index(op.f('ix_business_entities_entity_name'), table_name='business_entities')
    op.drop_table('business_entities')
    op.drop_table('backup_records')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_students_phone'), table_name='students')
    op.drop_index('ix_students_name_district', table_name='students')
    op.drop_index(op.f('ix_students_name'), table_name='students')
    op.drop_index(op.f('ix_students_id_card_number'), table_name='students')
    op.drop_index(op.f('ix_students_district_county'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###

